# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0035_auto_20160624_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default=b'Sin nombre', max_length=128),
        ),
    ]
